version: "3.7"

services:
  openhab:
    image: "openhab/openhab:2.5.7"
    restart: unless-stopped
    network_mode: host
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "./storage/openhab_addons:/openhab/addons"
      - "./storage/openhab_conf:/openhab/conf"
      - "./storage/openhab_userdata:/openhab/userdata"
    environment:
      OPENHAB_HTTP_PORT: "8080"
      OPENHAB_HTTPS_PORT: "8443"
      EXTRA_JAVA_OPTS: "-Duser.timezone=Europe/Brussels"
