---
version: 2
jobs:
  build:
    # machine: true
    docker:
      # - image: circleci/golang:1.12.12-buster
      - image: mandy91/dotfiles-build:0.1
    steps:
      - checkout
      - setup_remote_docker

      - run:
          name: Set up docker
          command: |
            # @see https://stackoverflow.com/questions/45796661/docker-permission-denied-while-trying-to-connect-to-docker-daemon-with-local-ci/45796662#45796662
            if [[ $CIRCLE_SHELL_ENV == *"localbuild"* ]]; then
              echo "export s=sudo" >> $BASH_ENV
              echo "export docker='sudo docker'" >> $BASH_ENV
            else
              echo "export s=" >> $BASH_ENV
              echo "export docker='docker'" >> $BASH_ENV
            fi

      - run:
          name: Verify docker
          command: $docker --version


      - run:
          name: Chmod temp folder
          command: |
            # Local circleci needs this
            sudo chmod 777 -R /tmp
            sudo mkdir -p /home/circleci/project/
            sudo chmod 777 -R /home/circleci/project/

      - run:
          name: Shellcheck
          command: .circleci/shellcheck.sh


      - run:
          name: Hadolint
          command: .circleci/hadolint.sh

      - run:
          name: Yamllint
          command: .circleci/yamllint.sh
